version: '3'

services:

  server:
    image: osrf/ros:eloquent-desktop
    hostname: ros2-eloquent
    volumes:
      - ./data/node:/home/node
    command: bash -c "
           curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -        
        && apt -y install nodejs 
        && apt -y install nano vim
        && cd /home/node
        && npm install
        && npm run dev
        && bash
      "
#    entrypoint: /home/data/script.sh
    stdin_open: true
    tty: true
    ports:
       - 3000:3000

  talker:
    image: osrf/ros:eloquent-desktop
	command: ros2 run demo_nodes_cpp talker
#    command: bash -c "
#           source /opt/ros/eloquent/setup.bash
#        && cd /home/workspace/krobosoft_pkg 
#        && colcon build
#        && source /home/workspace/krobosoft_pkg/install/setup.bash
#        && ros2 run krobosoft_pkg krobosoft_node
#        && bash
#      "
    stdin_open: true
    tty: true
    volumes:
       - ./data/C++:/home/workspace/
    depends_on:
      - server
