version: '3'

services:

  server:
    image: osrf/ros:eloquent-desktop
    hostname: ros2-eloquent
    volumes:
      - ./data/node:/home/node
    command: bash -c "
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -        
        && apt -y install nodejs  
        && cd /home/node
        && npm init -y
        && npm install express --save
        && npm install rclnodejs --save
        && npm install nodemon --save
        && node main.js
        && bash
      "
#    entrypoint: /home/data/script.sh
    stdin_open: true
    tty: true
    ports:
       - 3000:3000

  talker:
    image: osrf/ros:eloquent-desktop
    command: ros2 run demo_nodes_cpp talker
    depends_on:
      - server
