version: '3'

services:

  server:
    image: osrf/ros:eloquent-desktop
    hostname: ros2-eloquent
    volumes:
      - ./data/node:/home/node
    command: bash -c "
           curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -        
        && apt -y install nodejs 
        && apt -y install nano vim
        && cd /home/node
        && npm install
        && npm run dev
        && bash
      "
    #entrypoint: /home/data/script.sh
    stdin_open: true
    tty: true
    ports:
       - 3000:3000

  talker_cpp:
    image: osrf/ros:eloquent-desktop
    ##command: ros2 run demo_nodes_cpp talker
    command: bash -c "
            source /opt/ros/eloquent/setup.bash
        && cd /home/workspace/krobosoft_pkg 
        && colcon build
        && source /home/workspace/krobosoft_pkg/install/setup.bash
        && ros2 run krobosoft_pkg krobosoft_cpp_node
        && bash
      "
    stdin_open: true
    tty: true
    volumes:
        - ./data/C++/krobosoft_pkg:/home/workspace/krobosoft_pkg
    depends_on:
      - server

  talker_python:
    image: osrf/ros:eloquent-desktop
    command: bash -c "
           source /opt/ros/eloquent/setup.bash
        && cd /home/workspace/krobosoft_python_package
        && colcon build
        && source /home/workspace/krobosoft_python_package/install/setup.bash
        && ros2 run krobosoft_python_package krobosoft_node
        && bash
      "
    stdin_open: true
    tty: true
    volumes:
       - ./data/Python/krobosoft_python_package:/home/workspace/krobosoft_python_package
    depends_on:
      - server
