version: '3'

services:

  postgres-cim:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PG_ADMIN_PASSWD}"
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    networks:
      - cim-network


  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWD}"
    ports:
      - "16543:80"
    depends_on:
      - postgres-cim
    networks:
      - cim-network


  server:
    image: osrf/ros:eloquent-desktop
    hostname: ros2-eloquent
    volumes:
      - ./data/server:/home/server
    command: bash -c "
           curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -        
        && apt -y install nodejs 
        && apt -y install nano vim
        && cd /home/server
        && npm install
        && npm run dev
        && bash "
    #entrypoint: /home/data/script.sh
    stdin_open: true
    tty: true
    ports:
       - 3000:3000
    networks:
       - cim-network

  sst1:
    build:
      context: ./python-ros2
    volumes:
        - ./data/stations/Python_stt1_package:/home/extern
    networks:
        - cim-network
  sst2:
    build:
      context: ./python-ros2
    volumes:
        - ./data/stations/Python_stt2_package:/home/extern
    networks:
        - cim-network
  sst3:
    build:
      context: ./python-ros2
    volumes:
        - ./data/stations/Python_stt3_package:/home/extern
    networks:
        - cim-network

networks: 
  cim-network:
    driver: bridge